# .github/workflows/deploy-backend.yml

name: Deploy Code Backend Lambda Functions

on:
  push:
    branches:
      - main

      env:
  ECR_REPOSITORY: momotaro-lex-bot
  AWS_REGION: ca-central-1
  IMAGE_TAG: ${{ github.sha }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_FOR_OIDC_ARN }}
          aws-region: ca-central-1

      # --------------------------------------------------------------------
      # Step 2: LOGIN TO AMAZON ECR
      # --------------------------------------------------------------------
      # This action automatically uses the temporary credentials from the OIDC role.
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      # --------------------------------------------------------------------
      # Step 3: BUILD, TAG, AND PUSH DOCKER IMAGE
      # --------------------------------------------------------------------
      # This step also automatically uses the temporary credentials.
      - name: Build, Tag, and Push Image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          ECR_REPOSITORY_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}"
          docker build -t $ECR_REPOSITORY_URI:latest .
          docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:${IMAGE_TAG}
          docker push $ECR_REPOSITORY_URI:latest
          docker push $ECR_REPOSITORY_URI:${IMAGE_TAG}

      # --------------------------------------------------------------------
      # Step 4: DEPLOY INFRASTRUCTURE VIA TERRAFORM
      # --------------------------------------------------------------------
      # Terraform will also use the assumed OIDC role's temporary credentials.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure