# .github/workflows/deploy-backend.yml

name: Deploy Code Backend Lambda Functions

on:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: momotaro-lex-bot
  AWS_REGION: ca-central-1
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for passwordless authentication to AWS
      contents: read  # Required for the checkout step

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # This requires a GitHub secret containing the ARN of the IAM role
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_FOR_OIDC_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build, Tag, and Push Image to ECR
        id: build-image
        # This is the key fix: tells the step to run from your project's directory
        working-directory: ./lambda_container_project 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          ECR_REPOSITORY_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}"
          
          # This build command now correctly finds the Dockerfile in the current directory
          docker build -t $ECR_REPOSITORY_URI:latest .
          
          docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:${IMAGE_TAG}
          docker push $ECR_REPOSITORY_URI:latest
          docker push $ECR_REPOSITORY_URI:${IMAGE_TAG}